"""Add user supplements tracking

Revision ID: 11181374d18a
Revises: 34f0cc15feda
Create Date: 2025-04-13 18:39:04.835145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11181374d18a'
down_revision = '34f0cc15feda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_supplements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplement_name', sa.String(length=50), nullable=False),
    sa.Column('date_taken', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['registered_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_supplements')
    # ### end Alembic commands ###
