"""Add user exercise tracking table

Revision ID: 34f0cc15feda
Revises: 70689c17228c
Create Date: 2025-04-13 16:41:14.788417

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34f0cc15feda'
down_revision = '70689c17228c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('gym', sa.Integer(), nullable=True),
    sa.Column('running', sa.Integer(), nullable=True),
    sa.Column('yoga', sa.Integer(), nullable=True),
    sa.Column('zumba', sa.Integer(), nullable=True),
    sa.Column('hiit', sa.Integer(), nullable=True),
    sa.Column('cardio', sa.Integer(), nullable=True),
    sa.Column('cycling', sa.Integer(), nullable=True),
    sa.Column('swimming', sa.Integer(), nullable=True),
    sa.Column('badminton', sa.Integer(), nullable=True),
    sa.Column('lawn_tennis', sa.Integer(), nullable=True),
    sa.Column('table_tennis', sa.Integer(), nullable=True),
    sa.Column('volleyball', sa.Integer(), nullable=True),
    sa.Column('basketball', sa.Integer(), nullable=True),
    sa.Column('cricket', sa.Integer(), nullable=True),
    sa.Column('football', sa.Integer(), nullable=True),
    sa.Column('walking', sa.Integer(), nullable=True),
    sa.Column('other_sports', sa.Integer(), nullable=True),
    sa.Column('usual_movement', sa.Integer(), nullable=True),
    sa.Column('total_calories', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['registered_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_exercises')
    # ### end Alembic commands ###
