"""empty message

Revision ID: 70689c17228c
Revises: 7c404e4045a0
Create Date: 2025-04-12 17:16:27.486727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70689c17228c'
down_revision = '7c404e4045a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_weights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('date_recorded', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['registered_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_weights')
    # ### end Alembic commands ###
