"""Add step count to UserExercise model

Revision ID: 76244f7612d6
Revises: 11181374d18a
Create Date: 2025-04-13 21:30:13.895263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76244f7612d6'
down_revision = '11181374d18a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercises', schema=None) as batch_op:
        batch_op.add_column(sa.Column('step_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_exercises', schema=None) as batch_op:
        batch_op.drop_column('step_count')

    # ### end Alembic commands ###
